# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data + Donuts LA
description: > # this means to ignore newlines until "baseurl:"
    Changing local government from the ground up.
email: "data-donuts@compiler.la"
address: ""
twitter: datadonutsla
github: "compilerla/data-donuts"
youtube: "youtube.com/channel/UC_mAa07EdkkGCn48lq0yj3Q"

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://datadonuts.la" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html